version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
before_build:
  - cmd: dotnet restore
build:
  verbosity: minimal
only_commits:
  files:
    - src/
deploy:
  - provider: GitHub
    auth_token:
      secure: djcUXsjzGm1mZ4rPTUfn1Zf13ZPNK3ole3tE9cN79ts9SbFIYKU0g2kHM52i3mOh
    on:
      branch: master
      appveyor_repo_tag: true
