name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  workflow_dispatch:
    branches:
    - master
    paths:
     - '.github/**'
     - 'src/**'
     - build.cake
     - CodeCoverage.runsettings
     - dotnet-tools.json
     - global.json
     - Key.snk
     - Paseto.sln
  pull_request:
    branches:
    - master
    paths:
     - 'src/**'
     - build.cake
     - CodeCoverage.runsettings
     - dotnet-tools.json
     - global.json
     - Key.snk
     - Paseto.sln
  release:
    types:
    - published

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Set the build number in MinVer
  MINVERBUILDMETADATA: build.${{github.run_number}}
  # Set artifacts directory
  BUILD_ARTIFACT_PATH: './Artifacts'

jobs:
  build:
    name: Build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Git Fetch Tags'
      run: git fetch --tags
    - name: 'Install .NET SDK'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
    - name: '.NET Restore'
      run: dotnet tool restore
    - name: 'Build Project'
      run: dotnet cake --target=Build
    - name: 'Run Unit Tests'
      run: dotnet cake --target=Test
    - name: 'Dir output'
      run: dir tests\Paseto.Tests\bin\Release\net6.0
    - name: 'Run Unit Tests'
      run: dotnet test -f net6.0 --no-restore --logger trx -r ${{env.BUILD_ARTIFACT_PATH}} --settings "CodeCoverage.runsettings"
      if: ${{ false }} # always skip since coverage is somehow always empty in GitHub Actions
    - name: 'Run Test Report'
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: tests/Paseto.Tests
        report_name: paseto_dotnet_tests
        report_title: Paseto.NET Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gist_name: paseto_dotnet_tests.md
        gist_badge_label: 'Paseto Tests: %Counters_passed%/%Counters_total%'
        gist_token: ${{ secrets.GIST_TOKEN }}
      if: ${{ false }} # always skip due to 65K limit
    - name: 'Pack NuGet'
      run: dotnet cake --target=Pack
    - name: 'Publish Artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.os}}
        path: ${{env.BUILD_ARTIFACT_PATH}}

  coverage:
    name: 'Process Coverage'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Download Artifact'
      uses: actions/download-artifact@v2
    - name: 'Upload Coverage'
      uses: codecov/codecov-action@v2
      with:
        file: coverage.cobertura.xml
        fail_ci_if_error: false
